openapi: 3.1.0
x-stoplight:
  id: qh8kuxqhpnhwx
info:
  title: commons.v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
  parameters:
    page-index:
      name: pageIndex
      in: query
      schema:
        type: integer
        example: 1
        minimum: 1
        default: 1
      description: ページ数
      allowEmptyValue: true
    page-size:
      name: pageSize
      in: query
      schema:
        type: integer
        default: 10
        example: 10
        minimum: 1
      description: 表示数
      allowEmptyValue: true
    sort-column:
      name: sortColumn
      in: query
      required: false
      schema:
        type: string
        example: ComponentName
      description: ソートするカラム名
    sort-order:
      name: sortOrder
      in: query
      schema:
        type: string
        enum:
          - ASC
          - DESC
        example: ASC
      description: ソート順(ASC、DESC)
    filter-column:
      name: filter-column
      in: query
      required: false
      schema:
        type: string
      description: フィルター項目
    filter-query:
      name: filter-query
      in: query
      required: false
      schema:
        type: string
      description: フィルター内容
