openapi: 3.1.0
x-stoplight:
  id: qh8kuxqhpnhwx
info:
  title: commons.v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
  parameters:
    page-index:
      name: pageIndex
      in: query
      schema:
        type: integer
        example: 1
        minimum: 1
        default: 1
      description: ページ数
      allowEmptyValue: true
    page-size:
      name: pageSize
      in: query
      schema:
        type: integer
        default: 10
        example: 10
        minimum: 1
      description: 表示数
      allowEmptyValue: true
