get:
  summary: 電子部品リストの在庫情報取得
  tags:
    - inventories
  operationId: fetchComponentsInventory
  parameters:
    - $ref: "../parts-component/models.yaml#/components/parameters/componentIdQuery"
  responses:
    200:
      description: 取得成功
      content:
        application/json:
          schema:
            $ref: "./responses.yaml#/components/schemas/fetchComponentsInventoryResponse"
    400:
      description: |-
        - 電子部品IDが不正
    404:
      description: |-
        - 電子部品IDが存在しない
