openapi: 3.0.3
info:
  title: "在庫モデル"
  version: "1.0"
paths: {}
components:
  schemas:
    quantity:
      title: 個数
      type: integer
      example: 3
      minimum: 0

    remarks:
      title: 備考
      type: string
      example: "破損したため在庫を減らす"

    removeType:
      title: 在庫削除イベント種類
      description: |-
        紛失
        破棄
        使用
      type: string
      enum:
        - "lost"
        - "scrap"
        - "use"
