openapi: 3.0.3
info:
  title: ""
  version: "v1"
paths: {}
components:
  schemas:
    registryComponentInventoryRequest:
      title: 電子部品の在庫登録リクエスト
      type: object
      properties:
        quantity:
          $ref: "./models.yaml#/components/schemas/quantity"
        remarks:
          $ref: "./models.yaml#/components/schemas/remarks"
      required:
        - quantity
        - remarks

    removeComponentInventoryRequest:
      title: 電子部品の在庫削除リクエスト
      type: object
      properties:
        quantity:
          $ref: "./models.yaml#/components/schemas/quantity"
        remarks:
          $ref: "./models.yaml#/components/schemas/remarks"
        type:
          $ref: "./models.yaml#/components/schemas/removeType"
      required:
        - quantity
        - remarks
        - type
