openapi: 3.0.3
info:
  title: ""
  version: "v1"
paths: {}
components:
  schemas:
    fetchComponentsInventoryResponse:
      title: 電子部品リストの在庫情報を返す
      allOf:
        - $ref: ../common/models.yaml#/components/schemas/baseResponse
        - type: object
          properties:
            data:
              title: FetchComponentsInventoryArray
              type: array
              items:
                title: FetchComponentsInventoryData
                type: object
                properties:
                  componentId:
                    $ref: "../parts-component/models.yaml#/components/schemas/componentId"
                  event:
                    $ref: "./models.yaml#/components/schemas/inventoryChangeEvent"
                required:
                  - componentId
                  - event

    fetchComponentInventoryResponse:
      title: 電子部品の在庫情報を返す
      allOf:
        - $ref: ../common/models.yaml#/components/schemas/baseResponse
        - type: object
          properties:
            data:
              title: FetchComponentInventoryDataList
              type: array
              items:
                $ref: "./models.yaml#/components/schemas/inventoryChangeEvent"

    registryComponentInventoryResponse:
      title: 電子部品の在庫登録レスポンス
      allOf:
        - $ref: "../common/models.yaml#/components/schemas/baseResponse"
        - type: object
          properties:
            data:
              title: RegistryComponentInventoryData
              type: object
              properties:
                id:
                  $ref: "./models.yaml#/components/schemas/inventoryChangeEventId"
                quantity:
                  $ref: "./models.yaml#/components/schemas/quantity"
              required:
                - id
                - quantity

    removeComponentInventoryResponse:
      title: 電子部品の在庫削除レスポンス
      allOf:
        - $ref: "../common/models.yaml#/components/schemas/baseResponse"
        - type: object
          properties:
            data:
              title: RemoveComponentInventoryData
              type: object
              properties:
                id:
                  $ref: "./models.yaml#/components/schemas/inventoryChangeEventId"
                quantity:
                  $ref: "./models.yaml#/components/schemas/quantity"
              required:
                - id
                - quantity
