post:
  summary: 電子部品在庫追加
  description: |-
    - 電子部品在庫イベントに登録を記録
    - 電子部品在庫数を追加
  tags:
    - inventories
  operationId: registryComponentInventory
  parameters:
    - $ref: "../parts-component/models.yaml#/components/parameters/componentId"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "./requests.yaml#/components/schemas/registryComponentInventoryRequest"
  responses:
    200:
      description: 追加成功
      headers:
        Location:
          description: 在庫変更イベントID
          schema:
            type: string
            format: uri
            example: "https://xxxx/components/{componentId}/inventories/{inventoryId}"
      content:
        application/json:
          schema:
            $ref: "./responses.yaml#/components/schemas/registryComponentInventoryResponse"
    400:
      description: |-
        - 電子部品IDが不正
    404:
      description: |-
        - 電子部品IDが存在しない
