openapi: 3.0.3
info:
  title: "電子部品モデル"
  version: "1.0"
paths: {}
components:
  schemas:
    componentId:
      title: 電子部品ID
      description: |-
        C-6桁数字
      type: string
      pattern: ^C-\d{6}$
      example: "C-124286"

    componentName:
      title: 電子部品名
      type: string
      example: ＰＩＣマイコン　ＰＩＣ１６Ｆ１８２７－Ｉ／Ｐ

    componentModelName:
      title: 電子部品モデル名
      type: string
      example: PIC16F1827-I/P

    componentDescription:
      title: 部品説明
      type: string
      example: ナノワットXLPテクノロジーによる超低消費電力 Cコンパイラに最適化されたアーキテクチャ mTouchタッチセンサ入力  ■主な仕様 ・シリーズ：PIC16F ・電源電圧：1.8～5.5V ・コアサイズ：8bit ・命令長：14bit ・クロック：32MHz ・プログラムメモリ：4kW ・EEPROM：256B ・RAM：384B ・GPIO：16pin ・ADC：12Ch ・UART/USART：1Ch ・I2C：2Ch ・SPI：2Ch ・タイマ：5Ch ・オシレータ：内蔵/外付 ・パッケージ：DIP18  ・丸ピン18ピン(2227MC-18-03):P-00030 ・平ピン18ピン(2227-18-03)(10個単位販売):P-00008 ICソケット関連一覧 SSOPパッケージ→I-08400

    componentImageUrl:
      title: 部品画像
      type: string
      format: uri
      example: "https://akizukidenshi.com/img/goods/C/I-04430.jpg"

    componentImageList:
      title: 部品画像リスト
      type: array
      items:
        uniqueItems: true
        $ref: "#/components/schemas/componentImageUrl"

    #カテゴリー

    categoryId:
      title: 部品カテゴリーId
      description: |-
        - register
        - pic
      type: string
      example: "register"

    categoryName:
      title: 部品カテゴリー表示名
      description: |-
        - register: 抵抗
        - pic: マイコン
      type: string
      example: "マイコン"

    category:
      title: 部品カテゴリー
      type: object
      description: "電子部品のカテゴリー"
      properties:
        id:
          $ref: "#/components/schemas/categoryId"
        name:
          $ref: "#/components/schemas/categoryName"
      required:
        - id
        - name
      example:
        id: "register"
        name: "抵抗"

    #メーカー

    makerId:
      title: メーカーID
      description: |-
        M-国コード-6桁0左0埋め
      type: string
      pattern: ^M-[A-Z]{2,3}-\d{6}$
      example: "M-JPN-120138"

    makerName:
      title: メーカー名
      type: string
      example: "Microchip Technology Inc."

    maker:
      title: メーカー情報
      type: object
      properties:
        id:
          $ref: "#/components/schemas/makerId"
        name:
          $ref: "#/components/schemas/makerName"
      required:
        - id
        - name

    partsComponent:
      title: 電子部品
      type: object
      properties:
        id:
          $ref: "#/components/schemas/componentId"
        name:
          $ref: "#/components/schemas/componentName"
        modelName:
          $ref: "#/components/schemas/componentModelName"
        description:
          $ref: "#/components/schemas/componentDescription"
        category:
          $ref: "#/components/schemas/category"
        maker:
          $ref: "#/components/schemas/maker"
        images:
          $ref: "#/components/schemas/componentImageList"
      required:
        - id
        - name
        - modelName
        - category
        - maker

  parameters:
    componentId:
      name: componentId
      description: "## 電子部品ID"
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/componentId"

    categoryId:
      name: categoryId
      description: カテゴリーID
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/categoryId"

    makerId:
      name: makerId
      description: メーカーID
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/makerId"
