openapi: 3.0.3
info:
  title: PartsComponentsAPI.v1
  version: "1.0"
  description: |-
    # Components API
    電子部品のCRUDを行うWebAPI
tags:
  - name: components
servers:
  - url: "http://localhost:3000/api/v1/"
paths:
  "/components/{componentId}":
    parameters:
      - $ref: "./models.yaml#/components/parameters/componentId"
    get:
      summary: 電子部品情報取得
      tags:
        - components
      operationId: get-components-componentId
      description: 指定した電子部品IDと一致する電子部品情報を取得する
      responses:
        200:
          $ref: "./get-body.yaml#/components/responses/Ok"
        404:
          $ref: "./get-body.yaml#/components/responses/NotFound"

  "/components":
    get:
      summary: 電子部品情報取得
      description: 電子部品情報を取得する
      tags:
        - components
      operationId: get-components
      responses:
        "200":
          $ref: "./fetch-list-body.yaml#/components/responses/Ok"
        "204":
          $ref: "./fetch-list-body.yaml#/components/responses/NoContent"
      parameters:
        - $ref: ../common/models.yaml#/components/parameters/page-index
        - $ref: ../common/models.yaml#/components/parameters/page-size
        - $ref: ../common/models.yaml#/components/parameters/sort-column
        - $ref: ../common/models.yaml#/components/parameters/sort-order
        - $ref: ../common/models.yaml#/components/parameters/filter-column
        - $ref: ../common/models.yaml#/components/parameters/filter-query

    post:
      summary: 電子部品新規登録
      tags:
        - components
      operationId: post-components
      description: 電子部品を新規登録する
      requestBody:
        $ref: "./registry-body.yaml#/components/requestBodies/registry"
      responses:
        200:
          $ref: "./registry-body.yaml#/components/responses/Ok"
        400:
          $ref: "./registry-body.yaml#/components/responses/BadRequest"
        404:
          $ref: "./registry-body.yaml#/components/responses/NotFound"
