openapi: 3.0.3
info:
  title: PartsComponentsAPI.v1
  version: "1.0"
  description: |-
    # Components API
    電子部品のCRUDを行うWebAPI
tags:
  - name: components
servers:
  - url: "http://localhost:3000/api/v1/"
paths:
  "/components":
    get:
      summary: 電子部品情報一覧取得
      description: 電子部品情報を取得する
      tags:
        - components
      operationId: fetchComponents
      responses:
        200:
          $ref: "./fetch-components.yaml#/components/responses/Ok"
        204:
          description: "NotContent"
      parameters:
        - $ref: ../common/models.yaml#/components/parameters/pageIndex
        - $ref: ../common/models.yaml#/components/parameters/pageSize
        - $ref: ../common/models.yaml#/components/parameters/sortColumn
        - $ref: ../common/models.yaml#/components/parameters/sortOrder
        - $ref: ../common/models.yaml#/components/parameters/filterColumn
        - $ref: ../common/models.yaml#/components/parameters/filterQuery

    post:
      summary: 電子部品新規登録
      tags:
        - components
      operationId: registryComponents
      description: 電子部品を新規登録する
      requestBody:
        $ref: "./registry-body.yaml#/components/requestBodies/registry"
      responses:
        201:
          $ref: "./registry-body.yaml#/components/responses/Create"
        400:
          description: |-
            ### CRE40001
            電子部品がすでに存在する
        404:
          description: |-
            ### CRE40401
            カテゴリーが存在しない

            ### CRE40402
            メーカーが存在しない

  "/components/{componentId}":
    parameters:
      - $ref: "./models.yaml#/components/parameters/componentId"
    get:
      summary: 電子部品情報取得
      tags:
        - components
      operationId: fetchComponent
      description: 指定した電子部品IDと一致する電子部品情報を取得する
      responses:
        200:
          $ref: "./fetch-component.yaml#/components/responses/Ok"
        404:
          description: "NotFound"
