openapi: 3.0.2
info:
  title: "メーカー新規登録"
  version: "v1"
paths: {}
components:
  requestBodies:
    request:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/registryMakerRequest"

  responses:
    Create:
      description: メーカー新規登録レスポンス
      headers:
        Location:
          description: 生成したメーカーのURL
          schema:
            type: string
            format: uri
            example: "https://xxx/makers/MicrochipTechnologyInc"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/registryMakerResponse"

  schemas:
    registryMakerRequest:
      title: メーカー新規登録リクエスト
      type: object
      properties:
        id:
          $ref: "./models.yaml#/components/schemas/makerId"
      required:
        - id

    registryMakerResponse:
      title: メーカー新規登録レスポンス
      allOf:
        - $ref: "../common/models.yaml#/components/schemas/baseResponse"
        - type: object
          properties:
            data:
              type: object
              properties:
                makerId:
                  $ref: "./models.yaml#/components/schemas/makerId"
              required:
                - makerId
