openapi: 3.0.2
info:
  title: ""
  version: "v1"
paths: {}
components:
  schemas:
    registryComponentRequest:
      title: 電子部品新規登録リクエスト
      allOf:
        - $ref: "./models.yaml#/components/schemas/partsComponent"
      properties:
        categoryId:
          $ref: "../parts-component/models.yaml#/components/schemas/categoryId"
        id:
          readOnly: true
        category:
          readOnly: true
      required:
        - categoryId

    registryCategoryRequest:
      title: カテゴリー新規登録リクエスト
      type: object
      properties:
        id:
          $ref: "./models.yaml#/components/schemas/categoryId"
        name:
          $ref: "./models.yaml#/components/schemas/categoryName"
      required:
        - id
        - name

    registryMakerRequest:
      title: メーカー新規登録リクエスト
      type: object
      properties:
        id:
          $ref: "./models.yaml#/components/schemas/makerId"
      required:
        - id
