openapi: 3.0.3
info:
  title: ""
  version: "v1"
paths: {}
components:
  schemas:
    registryComponentRequest:
      title: 電子部品新規登録リクエスト
      allOf:
        - $ref: "./models.yaml#/components/schemas/partsComponent"
      properties:
        categoryId:
          $ref: "../parts-component/models.yaml#/components/schemas/categoryId"
        makerId:
          $ref: "../parts-component/models.yaml#/components/schemas/makerId"
        id:
          readOnly: true
          allOf:
            - $ref: "./models.yaml#/components/schemas/componentId"
        category:
          readOnly: true
          allOf:
            - $ref: "./models.yaml#/components/schemas/category"
        maker:
          readOnly: true
          allOf:
            - $ref: "./models.yaml#/components/schemas/maker"
      required:
        - categoryId
        - makerId

    updateComponentRequest:
      title: 電子部品更新リクエスト
      type: object
      properties:
        name:
          $ref: "../parts-component/models.yaml#/components/schemas/componentName"
        modelName:
          $ref: "../parts-component/models.yaml#/components/schemas/componentModelName"
        description:
          $ref: "../parts-component/models.yaml#/components/schemas/componentDescription"
        images:
          $ref: "../parts-component/models.yaml#/components/schemas/componentImageList"
        categoryId:
          $ref: "../parts-component/models.yaml#/components/schemas/categoryId"
        makerId:
          $ref: "../parts-component/models.yaml#/components/schemas/makerId"

    registryCategoryRequest:
      title: カテゴリー新規登録リクエスト
      type: object
      properties:
        id:
          $ref: "./models.yaml#/components/schemas/categoryId"
        name:
          $ref: "./models.yaml#/components/schemas/categoryName"
      required:
        - id
        - name

    registryMakerRequest:
      title: メーカー新規登録リクエスト
      type: object
      properties:
        countryCode:
          $ref: "./models.yaml#/components/schemas/countryCode"
        name:
          $ref: "./models.yaml#/components/schemas/makerName"
      required:
        - countryCode
        - name
