openapi: 3.1.0
x-stoplight:
  id: z5fs5e7ybz99x
info:
  title: 秋月電子連携API
  version: '1.0'
  summary: 秋月電子通販サイトの情報を取得、注文情報の取得等を行う
  description: |
    # 秋月電子連携API
    ## 目的

    ## 共通処理
    ### 1.
    ### 2. 
  termsOfService: 'https://akizukidenshi.com/catalog/top.aspx'
servers:
  - url: 'http://localhost:3000/api/v1/akizuki/'
paths:
  '/catalogs/{catalogId}':
    get:
      summary: カタログ情報取得
      tags: []
      responses:
        '200':
          description: |-
            ## OK(200) 成功
            電子部品情報取得成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../common/models/success-response.yaml
                  - type: object
                    properties:
                      data:
                        $ref: ../parts-component/models/parts-component.yaml
        '400':
          description: |-
            ## Bad Request(400) 不正リクエスト
            ### エラーコード:C400
            入力パラメータ不正
          content:
            application/json:
              schema:
                $ref: ../common/models/error-response.yaml
              examples:
                C400:
                  value:
                    success: false
                    data: {}
                    errors:
                      code: AKE0101
                      message: 予期せぬエラーが発生しました
                      stack: IOException StreamReader.Read at 102 line...
        '404':
          description: |-
            ## Not Found(404) 存在しない
            ### エラーコード: AKE0101
              カタログIDが存在しない
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../common/models/error-response.yaml
              examples: {}
        '500':
          description: |-
            ## Internal Server Error(500) サーバー内エラー
            ### C999

            ### エラーコード:AKE0102
            パース処理に失敗

            ### エラーコード:AKE0103
            通販サイトの接続に失敗
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../common/models/error-response.yaml
              examples: {}
      operationId: get-catalogs-catalogId
      description: |-
        # カタログ情報取得 API
        ## 目的
        1. パスパラメーターのカタログIDを基に秋月電子の通販サイトを検索する

        2. 電子部品が存在した場合、ページ内容をパースする

        3. パースした結果をレスポンスとして返す
      x-internal: true
    parameters:
      - $ref: '#/components/parameters/catalogId'
  /orders:
    get:
      summary: 購入履歴取得
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/fetch-order-success-response'
        '400':
          description: |-
            ## Bad Request
            ### AKE0201
            htmlのファイル容量エラー

            ### AKE0202
            htmlファイルフォーマットエラー
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../common/models/error-response.yaml
        '500':
          description: |-
            ## Internal Server Error
            ### C999
            予期せぬエラー
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../common/models/error-response.yaml
      operationId: get-catalogs-orders
      x-internal: true
      description: |-
        # 購入履歴取得API
        ## 秋月電子の購入履歴を取得する
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
        description: |-
          ## 秋月電子の購入履歴ページのhtmlファイル
          https://akizukidenshi.com/catalog/customer/history.aspx
    parameters: []
  /orders/details:
    get:
      summary: 購入履歴詳細取得
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/fetch-order-detail-success-response'
        '400':
          description: |-
            ## Bad Request
            ### C400
            入力パラメターエラー

            ### AKE0301
            htmlのファイル容量エラー

            ### AKE0302
            htmlファイルフォーマットエラー
        '500':
          description: |-
            ## Internal Server Error
            ### C999
            予期せぬエラー
      operationId: get-orders-details
      x-internal: true
      description: |-
        # 購入履歴詳細取得API
        ## 秋月電子の購入履歴詳細を取得する
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties: {}
        description: |-
          ## 秋月電子の購入履歴詳細のhtmlファイル
          https://akizukidenshi.com/catalog/customer/historydetail.aspx?order_id=E230617-031873-01
    parameters: []
components:
  schemas:
    orderId:
      title: 注文ID
      x-stoplight:
        id: 9sznsfy7vrad8
      type: object
      description: '## 秋月電子で注文した際のID'
      properties:
        orderId:
          type: string
          description: 注文ID
          pattern: '^E\d{6}-\d{6}-\d{2}$'
          minLength: 17
          maxLength: 17
          example: E230617-031873-01
      required:
        - orderId
      x-internal: true
    order-model:
      allOf:
        - $ref: '#/components/schemas/orderId'
          description: 注文ID
        - $ref: '#/components/schemas/slipNumber-model'
        - $ref: '#/components/schemas/orderDate'
          x-stoplight:
            id: r54p1wuqxpxld
        - type: object
          x-stoplight:
            id: 6981jbyhsm9su
          properties:
            components:
              type: array
              x-stoplight:
                id: nirl5gwii69wb
              items:
                $ref: '#/components/schemas/akizuki-component'
                x-stoplight:
                  id: yawz9sokm4gn3
      title: 注文モデル
      x-internal: true
      description: '## 秋月電子で注文した注文モデル'
    slipNumber-model:
      title: 伝票番号
      x-stoplight:
        id: 1oj8xsipw2msc
      type: object
      description: '## 秋月電子で注文した伝票番号'
      x-internal: true
      properties:
        slipNumber:
          type: integer
          example: 569321486926
          minimum: 12
          description: 伝票番号
      required:
        - slipNumber
    catalogId:
      title: catalogId
      x-stoplight:
        id: hpyx9c3rxim69
      type: object
      description: |-
        ## カタログコード
        秋月電子の通販コード
      x-internal: true
      properties:
        catalogId:
          type: string
          x-stoplight:
            id: y1qh0cysv87q4
          description: 通販コード
          pattern: '^[A-Z]-\d{5}$'
          minLength: 7
          maxLength: 7
          example: M-18246
      required:
        - catalogId
    akizuki-component:
      title: akizuki-component
      x-stoplight:
        id: p71zxuqi724b2
      allOf:
        - $ref: '#/components/schemas/catalogId'
          x-stoplight:
            id: a3ownw3uh9qwi
          description: カタログID
        - $ref: ../parts-component/models/componentId.yaml
          x-stoplight:
            id: fbtkvabi26qe0
        - $ref: ../parts-component/models/componentName.yaml
          x-stoplight:
            id: jsw108c0fetiq
      description: '## 秋月電子の電子部品情報'
      x-internal: true
    orderDate:
      title: orderDate
      x-stoplight:
        id: z73vn0r9xj0i0
      type: object
      description: '## 秋月電子で注文した日'
      properties:
        orderDate:
          type: string
          x-stoplight:
            id: c85qvm97n7w4n
          format: date
          example: '2023-12-3'
          description: 秋月電子で注文した日
      required:
        - orderDate
      x-internal: true
    akizuki-order-component:
      title: akizuki-order-component
      x-stoplight:
        id: h1y4kcyv8rd5h
      description: '## 秋月電子で注文した電子部品情報'
      x-internal: true
      allOf:
        - $ref: '#/components/schemas/akizuki-component'
        - $ref: ../inventory/models/quantity.yaml
          x-stoplight:
            id: vf5uq2zydis22
        - $ref: ../inventory/models/unit.yaml
          x-stoplight:
            id: gcgs9k4enneu5
  parameters:
    catalogId:
      name: catalogId
      in: path
      required: true
      schema:
        type: string
        pattern: '^[A-Z]-\d{5}$'
        example: I-12467
        minLength: 7
        maxLength: 7
      description: '## 秋月電子のカタログID'
    orderId:
      name: orderId
      in: path
      required: true
      schema:
        type: string
        example: E230617-031873-01
        pattern: '^E\d{6}-\d{6}-\d{2}$'
        minLength: 17
        maxLength: 17
      description: 秋月電子で注文した注文ID
  responses:
    fetch-order-success-response:
      description: '## 秋月電子注文情報取得成功レスポンス'
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../common/models/success-response.yaml
                x-stoplight:
                  id: q1tbcy8k9ffc8
              - type: object
                x-stoplight:
                  id: 0jdulg5wrqrra
                properties:
                  data:
                    type: array
                    x-stoplight:
                      id: 3h6g3p4wowirl
                    items:
                      $ref: '#/components/schemas/order-model'
                      x-stoplight:
                        id: sgt5e6rjx3bru
                required:
                  - data
          examples: {}
    fetch-order-detail-success-response:
      description: '## 秋月電子の注文詳細取得の成功レスポンス'
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../common/models/success-response.yaml
                x-stoplight:
                  id: bp4g7rj2lbkj6
              - type: object
                x-stoplight:
                  id: 1i9n93e0i62iw
                properties:
                  data:
                    x-stoplight:
                      id: pmymvebpqrcz2
                    allOf:
                      - $ref: '#/components/schemas/orderId'
                      - $ref: '#/components/schemas/slipNumber-model'
                        x-stoplight:
                          id: 594gfkkzegbzm
                      - $ref: '#/components/schemas/orderDate'
                        x-stoplight:
                          id: e2dcot906vmwv
                      - type: object
                        x-stoplight:
                          id: 51tflmvyyocu9
                        properties:
                          components:
                            type: array
                            x-stoplight:
                              id: zwsiry3uoez01
                            items:
                              $ref: '#/components/schemas/akizuki-order-component'
                              x-stoplight:
                                id: hecrdlzf8s5nl
                        required:
                          - components
                required:
                  - data
      headers: {}
x-internal: true
