openapi: 3.0.3
info:
  title: "プロジェクト定義"
  version: "1.0"
paths: {}
components:
  schemas:
    # プロジェクト系
    projectId:
      title: プロジェクトID
      type: string
      pattern: ^P-\d{6}$
      example: "P-123456"

    projectName:
      title: プロジェクト名
      description: |-
        1行で記載する
      type: string
      maxLength: 30
      example: "VitalStrike"

    projectSummary:
      title: プロジェクト要約
      type: string
      description: |-
        2~3行で説明するプロジェクトの要約
      maxLength: 100
      example: "光学センサーを用いたトリガーセンサーの開発"

    projectDescription:
      title: プロジェクト説明
      description: |-
        複数行で説明するプロジェクトの説明
      type: string
      example: "磁気センサーIC(ホールIC)リニア型UGN3503EUAでは取り付けに難があり..."

    tag:
      title: タグ
      type: string
      example: "GitHub"
      maxLength: 15

    linkTitle:
      title: リンクのタイトル
      type: string
      example: "パーツの写真"
      maxLength: 20

    projectExternalLink:
      title: 関連外部リンク
      type: object
      properties:
        link:
          title: リンク
          type: string
          format: uri
          example: "https://airsoft97.com/products/detail/10597"
        tag:
          $ref: "#/components/schemas/tag"
        title:
          $ref: "#/components/schemas/linkTitle"
      required:
        - link

    projectImg:
      title: プロジェクト画像
      type: object
      properties:
        url:
          title: 画像URL
          type: string
          format: uri
          example: "https://demo.part-db.de/img/part_placeholder.svg"
        tag:
          $ref: "#/components/schemas/tag"
        title:
          $ref: "#/components/schemas/linkTitle"
      required:
        - url

    projectStatus:
      title: プロジェクトステータス
      type: string
      description: |-
        - planning
          - 構想
        - processing
          - 進行中
        - pause
          - 一時停止
        - cancel
          - 中止
        - complete
          - 完了
      example: "planning"

    createdAt:
      title: プロジェクト作成日時
      type: string
      format: date-time

    lastModified:
      title: プロジェクト最終変更日時
      type: string
      format: date-time

    project:
      title: プロジェクト
      type: object
      properties:
        id:
          $ref: "#/components/schemas/projectId"
        name:
          $ref: "#/components/schemas/projectName"
        summary:
          $ref: "#/components/schemas/projectSummary"
        status:
          $ref: "#/components/schemas/projectStatus"
        description:
          $ref: "#/components/schemas/projectDescription"
        tag:
          $ref: "#/components/schemas/tag"
        imgUrls:
          title: プロジェクト画像Urlリスト
          type: array
          items:
            $ref: "#/components/schemas/projectImg"
        externalLinks:
          title: 外部リンクリスト
          type: array
          items:
            $ref: "#/components/schemas/projectExternalLink"
        bomList:
          title: BOMリスト
          type: array
          items:
            $ref: "#/components/schemas/bom"
        createdAt:
          $ref: "#/components/schemas/createdAt"
        lastModified:
          $ref: "#/components/schemas/lastModified"
      required:
        - id
        - name
        - summary
        - status
        - createdAt
        - lastModified

    updateProjectFieldMask:
      title: プロジェクト更新フィールドマスク
      type: string
      enum:
        - name
        - summary
        - status
        - description
        - tag
        - imgUrls
        - externalLinks
        - bomList
      example: name

    # BOM系

    footPrintName:
      title: フットプリント名
      type: string
      example: "Capacitor_THT:C_Disc_D3.0mm_W1.6mm_P2.50mm"
      
    supplierName:
      title: 購入先名
      type: string
      example: "秋月電子"
    
    supplierUrl:
      title: 購入先URL
      type: string
      format: uri
      example: "https://akizukidenshi.com/catalog/g/g131275/"
    
    supplierModelId:
      title: 購入先の固有ID
      type: string
      example: "g131275"
    
    supplier:
      title: 購入先
      type: object
      properties:
        name:
          $ref: "#/components/schemas/supplierName"
        url:
          $ref: "#/components/schemas/supplierUrl"
        modelId:
          $ref: "#/components/schemas/supplierModelId"
      required:
        - url

    bomId:
      title: BOMId
      type: string
      description: |-
        BOMの識別ID
      pattern: ^B-\d{6}$
      example: "B-123456"

    bomRemarks:
      title: BOMの備考・注記
      type: string
      example: パスコン用

    bomRefName:
      title: BOMのリファレンス名
      type: string
      example: "C1"

    bom:
      title: BOM(BillOfMaterial)
      description: |-
        プロジェクトに必要なBOM
      type: object
      properties:
        id:
          $ref: "#/components/schemas/bomId"
        componentId:
          $ref: "../parts-component/models.yaml#/components/schemas/componentId"
        quantity:
          $ref: "../inventory/models.yaml#/components/schemas/quantity"
        footPrintName:
          $ref: "#/components/schemas/footPrintName"
        remarks:
          $ref: "#/components/schemas/bomRemarks"
        refName:
          $ref: "#/components/schemas/bomRefName"
        supplier:
          $ref: "#/components/schemas/supplier"
      required:
        - id
        - componentId
        - quantity

    bomForNewOrUpdate:
      title: 新規登録・更新リクエスト用 BOM(BillOfMaterial)
      description: |-
        プロジェクトに必要なBOM
      type: object
      properties:
        id:
          $ref: "#/components/schemas/bomId"
        componentId:
          $ref: "../parts-component/models.yaml#/components/schemas/componentId"
        quantity:
          $ref: "../inventory/models.yaml#/components/schemas/quantity"
        footPrintName:
          $ref: "#/components/schemas/footPrintName"
        remarks:
          $ref: "#/components/schemas/bomRemarks"
        refName:
          $ref: "#/components/schemas/bomRefName"
        supplier:
          $ref: "#/components/schemas/supplier"
      required:
        - componentId
        - quantity

    # 履歴系
    projectHistoryId:
      title: プロジェクト履歴ID
      type: string
      description: |
        履歴の識別ID。
        プロジェクトIDを含めた形式。
        例: P-123456-H-000123
      pattern: ^P-\d{6}-H-\d{6}$
      example: "P-123456-H-000123"

    

    projectHistoryChangeType:
      title: 変更種別
      type: string
      enum:
        - created
        - updated
        - deleted
        - restored
      example: updated

    projectHistory:
      title: プロジェクト履歴
      type: object
      properties:
        historyId:
          $ref: "#/components/schemas/projectHistoryId"
        projectId:
          $ref: "#/components/schemas/projectId"
        createdAt:
          $ref: "#/components/schemas/createdAt"
        message:
          title: 変更メッセージ
          type: string
          example: "BOMの抵抗を0603へ変更"
        changeType:
          $ref: "#/components/schemas/projectHistoryChangeType"
        changedFields:
          title: 変更されたフィールド
          type: array
          items:
            type: string
            example: "bomList"
      required:
        - historyId
        - projectId
        - createdAt

    jsonPatchOperation:
      title: JSON Patch Operation
      type: object
      properties:
        op:
          type: string
          enum: [add, remove, replace, move, copy, test]
        path:
          type: string
          example: "/bomList/0/quantity"
        from:
          type: string
          example: "/bomList/0"
        value:
          description: 変更値
          nullable: true
      required:
        - op
        - path

    jsonPatch:
      title: JSON Patch
      type: array
      items:
        $ref: "#/components/schemas/jsonPatchOperation"

    projectDiff:
      title: プロジェクト差分
      type: object
      properties:
        baseHistoryId:
          $ref: "#/components/schemas/projectHistoryId"
        previousHistoryId:
          $ref: "#/components/schemas/projectHistoryId"
        patch:
          $ref: "#/components/schemas/jsonPatch"
        summary:
          title: 要約
          type: object
          properties:
            totalChanges:
              type: integer
              example: 5
            added:
              type: integer
              example: 2
            removed:
              type: integer
              example: 1
            replaced:
              type: integer
              example: 2

  parameters:
    projectId:
      name: projectId
      description: "プロジェクトID"
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/projectId"

    historyId:
      name: historyId
      description: プロジェクト履歴ID
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/projectHistoryId"

    updateProjectFieldMask:
      name: fieldMask
      description: プロジェクト更新フィールドマスク
      in: query
      required: true
      schema:
        $ref: "#/components/schemas/updateProjectFieldMask"
