openapi: 3.0.3
info:
  title: "プロジェクト定義"
  version: "1.0"
paths: {}
components:
  schemas:
    # プロジェクト系
    projectId:
      title: プロジェクトID
      type: string
      pattern: ^P-\d{6}$
      example: "P-123456"

    projectName:
      title: プロジェクト名
      description: |-
        1行で記載する
      type: string
      maxLength: 30
      example: "VitalStrike"

    projectSummary:
      title: プロジェクト要約
      type: string
      description: |-
        2~3行で説明するプロジェクトの要約
      maxLength: 100

    projectDescription:
      title: プロジェクト説明
      description: |-
        複数行で説明するプロジェクトの説明
      type: string

    projectExternalLink:
      title: 関連外部リンク
      type: string
      format: uri

    projectStatus:
      title: プロジェクトステータス
      type: string
      description: |-
        - planning
          - 構想
        - processing
          - 進行中
        - pause
          - 一時停止
        - cancel
          - 中止
        - complete
          - 完了
      example: "planning"

    project:
      title: プロジェクト
      type: object
      properties:
        id:
          $ref: "#/components/schemas/projectId"
        name:
          $ref: "#/components/schemas/projectName"
        summary:
          $ref: "#/components/schemas/projectSummary"
        status:
          $ref: "#/components/schemas/projectStatus"
        description:
          $ref: "#/components/schemas/projectDescription"
        externalLink:
          $ref: "#/components/schemas/projectExternalLink"
        bomList:
          title: BOMリスト
          type: array
          items:
            $ref: "#/components/schemas/bom"
      required:
        - id
        - name
        - summary
        - status

    updateProjectFieldMask:
      title: プロジェクト更新フィールドマスク
      type: string
      enum:
        - name
        - summary
        - status
        - description
        - externalLink
      example: name

    # BOM系

    footPrintName:
      title: フットプリント名
      type: string
      example: "Capacitor_THT:C_Disc_D3.0mm_W1.6mm_P2.50mm"

    bomId:
      title: BOMId
      type: string
      description: |-
        BOMの識別ID
      pattern: ^B-\d{6}$
      example: "B-123456"

    bomRemarks:
      title: BOMの備考・注記
      type: string
      example: パスコン用

    bomRefName:
      title: BOMのリファレンス名
      type: string
      example: "C1"

    bom:
      title: BOM(BillOfMaterial)
      description: |-
        プロジェクトに必要なBOM
      type: object
      properties:
        id:
          $ref: "#/components/schemas/bomId"
        componentId:
          $ref: "../parts-component/models.yaml#/components/schemas/componentId"
        quantity:
          $ref: "../inventory/models.yaml#/components/schemas/quantity"
        footPrintName:
          $ref: "#/components/schemas/footPrintName"
        remarks:
          $ref: "#/components/schemas/bomRemarks"
        refName:
          $ref: "#/components/schemas/bomRefName"
      required:
        - id
        - componentId
        - quantity

  parameters:
    projectId:
      name: projectId
      description: "プロジェクトID"
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/projectId"

    updateProjectFieldMask:
      name: fieldMask
      description: プロジェクト更新フィールドマスク
      in: query
      required: true
      schema:
        $ref: "#/components/schemas/updateProjectFieldMask"
