openapi: 3.0.3
info:
  title: "project requests"
  version: "v1"
paths: {}
components:
  schemas:
    registryProjectRequest:
      title: プロジェクト登録リクエスト
      type: object
      properties:
        name:
          $ref: "./models.yaml#/components/schemas/projectName"
        summary:
          $ref: "./models.yaml#/components/schemas/projectSummary"
        description:
          $ref: "./models.yaml#/components/schemas/projectDescription"
        tag:
          $ref: "./models.yaml#/components/schemas/tag"
        imgUrls:
          title: プロジェクト画像リスト
          type: array
          items:
            $ref: "./models.yaml#/components/schemas/projectImg"
        externalLinks:
          title: 外部リンクリスト
          type: array
          items:
            $ref: "./models.yaml#/components/schemas/projectExternalLink"
      required:
        - name
        - summary

    updateProjectRequest:
      title: プロジェクト更新リクエスト
      description: |-
        - クエリパラメーターで指定された項目のみ更新内容に反映される。
          - 例外として、更新メッセージ`updateMessage`のみ値さえあれば更新履歴に登録される
      type: object
      properties:
        updateMessage:
          title: 更新メッセージ
          description: |-
            履歴に表示される
          type: string
          example: プロジェクト概要を追記
        name:
          $ref: "./models.yaml#/components/schemas/projectName"
        summary:
          $ref: "./models.yaml#/components/schemas/projectSummary"
        status:
          $ref: "./models.yaml#/components/schemas/projectStatus"
        description:
          $ref: "./models.yaml#/components/schemas/projectDescription"
        tag:
          $ref: "./models.yaml#/components/schemas/tag"
        imgUrls:
          title: プロジェクト画像Urlリスト
          type: array
          items:
            $ref: "./models.yaml#/components/schemas/projectImg"
        externalLinks:
          title: 外部リンクリスト
          type: array
          items:
            $ref: "./models.yaml#/components/schemas/projectExternalLink"
        bomList:
          title: BOMリスト
          type: array
          items:
            $ref: "./models.yaml#/components/schemas/bomForNewOrUpdate"
