openapi: 3.0.3
info:
  title: "project responses"
  version: "v1"
paths: {}
components:
  schemas:
    fetchProjectsResponse:
      title: プロジェクト一覧取得レスポンス
      allOf:
        - $ref: ../common/models.yaml#/components/schemas/pageResponse
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: "./models.yaml#/components/schemas/project"

    fetchProjectResponse:
      title: プロジェクト取得レスポンス
      allOf:
        - $ref: ../common/models.yaml#/components/schemas/baseResponse
        - type: object
          properties:
            data:
              $ref: "./models.yaml#/components/schemas/project"

    updateProjectResponse:
      title: プロジェクト更新レスポンス
      allOf:
        - $ref: ../common/models.yaml#/components/schemas/baseResponse
        - type: object
          properties:
            data:
              $ref: "./models.yaml#/components/schemas/project"

    registryProjectResponse:
      title: プロジェクト登録レスポンス
      allOf:
        - $ref: ../common/models.yaml#/components/schemas/baseResponse
        - type: object
          properties:
            data:
              title: 登録プロジェクトID
              type: object
              properties:
                projectId:
                  $ref: "./models.yaml#/components/schemas/projectId"
              required:
                - projectId
