openapi: 3.0.3
info:
  title: 秋月電子連携API
  version: "1.0"
  description: |
    # 秋月電子連携API
    秋月電子通販サイトの情報を取得、注文情報の取得等を行う
  termsOfService: "https://akizukidenshi.com/catalog/top.aspx"
servers:
  - url: "http://localhost:3000/api/v1/akizuki/"
tags:
  - name: "akizuki"

paths:
  "/catalogs/{catalogId}":
    get:
      summary: カタログ情報取得
      description: |-
        # カタログ情報取得 API
        1. パスパラメーターのカタログIDを基に秋月電子の通販サイトを検索する

        2. 電子部品が存在した場合、ページ内容をパースする

        3. メーカー名、カテゴリー名がDBに存在しなければ登録する
          - TODO この動きはどうかと。。。

        4. パースした結果をレスポンスとして返す
      tags: ["akizuki"]
      operationId: get-catalogs-catalogId
      parameters:
        - $ref: "./models.yaml#/components/parameters/catalogId"
      responses:
        200:
          $ref: "./catalogs-catalogId.get.yaml#/components/responses/Ok"
        400:
          $ref: "./catalogs-catalogId.get.yaml#/components/responses/BadRequest"
        404:
          $ref: "./catalogs-catalogId.get.yaml#/components/responses/NotFound"
        500:
          $ref: "./catalogs-catalogId.get.yaml#/components/responses/InternalServerError"

  /orders/upload:
    post:
      summary: 購入履歴取得
      description: |-
        # 購入履歴取得API
        ## 秋月電子の購入履歴を取得する
      tags: ["akizuki"]
      operationId: get-catalogs-orders
      requestBody:
        $ref: "./orders-upload.post.yaml#/components/requestBodies/request"
      responses:
        200:
          $ref: "./orders-upload.post.yaml#/components/responses/Ok"
        400:
          $ref: "./orders-upload.post.yaml#/components/responses/BadRequest"
        500:
          $ref: "./orders-upload.post.yaml#/components/responses/InternalServerError"

  /orders/details/upload:
    post:
      summary: 購入履歴詳細取得
      description: |-
        # 購入履歴詳細取得API
        ## 秋月電子の購入履歴詳細を取得する
      tags: ["akizuki"]
      operationId: get-orders-details
      requestBody:
        $ref: "./orders-details-upload.post.yaml#/components/requestBodies/request"
      responses:
        200:
          $ref: "./orders-details-upload.post.yaml#/components/responses/Ok"
        400:
          $ref: "./orders-details-upload.post.yaml#/components/responses/BadRequest"
        500:
          $ref: "./orders-details-upload.post.yaml#/components/responses/InternalServerError"

  /orders:
    post:
      summary: 秋月電子の注文登録
      description: |-
        ## 秋月電子の注文を登録する

        1. DBに登録する
        2. 入荷登録にここで登録した注文IDを使用する
      operationId: post-orders
      tags:
        - "akizuki"
      requestBody:
        $ref: "./orders.post.yaml#/components/requestBodies/request"
      responses:
        200:
          $ref: "orders.post.yaml#/components/responses/Ok"
        400:
          $ref: "orders.post.yaml#/components/responses/BadRequest"
        404:
          $ref: "orders.post.yaml#/components/responses/NotFound"
        500:
          $ref: "orders.post.yaml#/components/responses/InternalServerError"

    get:
      summary: 秋月電子の注文取得
      description: |
        ## 秋月電子の注文を取得する
      parameters:
        - $ref: ../common/models.yaml#/components/parameters/page-index
        - $ref: ../common/models.yaml#/components/parameters/page-size
      tags:
        - "akizuki"
      operationId: get-orders
      responses:
        200:
          $ref: "./orders.get.yaml#/components/responses/Ok"
        204:
          $ref: "./orders.get.yaml#/components/responses/NoContent"
        500:
          $ref: "./orders.get.yaml#/components/responses/InternalServerError"
