openapi: 3.0.3
info:
  title: ""
  version: "1.0"
paths: {}
components:
  schemas:
    catalogId:
      title: 秋月電子のカタログID
      type: string
      pattern: '^[A-Z]-\d{5}$'
      example: I-12467
      minLength: 7
      maxLength: 7

    orderId:
      title: 秋月電子の注文ID
      type: string
      example: E230617-031873-01
      pattern: '^E\d{6}-\d{6}-\d{2}$'
      minLength: 17
      maxLength: 17

    orderDate:
      title: 秋月電子で注文した日
      type: string
      format: date
      example: "2023-12-3"

    akizuki-component:
      title: 秋月電子の電子部品情報
      type: object
      properties:
        catalogId:
          $ref: "#/components/schemas/catalogId"
        componentId:
          $ref: ../parts-component/models.yaml#/components/schemas/componentId

    order-model:
      title: 秋月電子で注文した注文モデル
      type: object
      properties:
        orderId:
          $ref: "#/components/schemas/orderId"
        orderDate:
          $ref: "#/components/schemas/orderDate"
        components:
          type: array
          items:
            $ref: "#/components/schemas/akizuki-component"

  parameters:
    catalogId:
      name: catalogId
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/catalogId"

    orderId:
      name: orderId
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/orderId"
