openapi: 3.0.3
info:
  title: 秋月電子連携API
  version: "1.0"
  description: |
    # 秋月電子連携API
    秋月電子通販サイトの情報を取得、注文情報の取得等を行う
  termsOfService: "https://akizukidenshi.com/catalog/top.aspx"
servers:
  - url: "http://localhost:3000/api/v1/akizuki/"
tags:
  - name: "catalogs"

paths:
  /catalogs/{catalogId}:
    get:
      summary: カタログ情報取得
      description: |-
        1. カタログIDを基に秋月電子の通販サイトを検索する

        2. 電子部品が存在した場合、ページ内容をパースする

        3. メーカーID、カテゴリーが未登録の場合、その情報を`unRegistered`に返す
      tags:
        - "catalogs"
      operationId: fetchComponentByAkizukiCatalogId
      parameters:
        - $ref: "./models.yaml#/components/parameters/catalogId"
      responses:
        200:
          $ref: "./fetch-component-by-catalog-id.yaml#/components/responses/Ok"
        400:
          description: |-
            - カタログIDが不正
        404:
          description: |-
            - カタログIDが存在しない
        500:
          description: |-
            ### エラーコード:AKE0102
            パース処理に失敗

            ### エラーコード:AKE0103
            通販サイトの接続に失敗

  /orders/upload:
    post:
      summary: 購入履歴取得
      description: |-
        # 購入履歴取得API
        ## 秋月電子の購入履歴を取得する
      tags: ["akizuki"]
      operationId: get-catalogs-orders
      requestBody:
        $ref: "./orders-upload.post.yaml#/components/requestBodies/request"
      responses:
        200:
          $ref: "./orders-upload.post.yaml#/components/responses/Ok"
        400:
          description: |-
            ### AKE0201
            htmlのファイル容量エラー

            ### AKE0202
            htmlファイルフォーマットエラー
        500:
          description: |-
            TODO

  /orders/details/upload:
    post:
      summary: 購入履歴詳細取得
      description: |-
        # 購入履歴詳細取得API
        ## 秋月電子の購入履歴詳細を取得する
      tags: ["akizuki"]
      operationId: get-orders-details
      requestBody:
        $ref: "./orders-details-upload.post.yaml#/components/requestBodies/request"
      responses:
        200:
          $ref: "./orders-details-upload.post.yaml#/components/responses/Ok"
        400:
          description: |-
            ## Bad Request
            ### C400
            入力パラメターエラー

            ### AKE0301
            htmlのファイル容量エラー

            ### AKE0302
            htmlファイルフォーマットエラー
        500:
          description: |-
            ## Internal Server Error
            ### C999
            予期せぬエラー

            ### AKE0303
            htmlファイル解析失敗エラー

  /orders:
    post:
      summary: 秋月電子の注文登録
      description: |-
        ## 秋月電子の注文を登録する

        1. DBに登録する
        2. 入荷登録にここで登録した注文IDを使用する
      operationId: post-orders
      tags:
        - "akizuki"
      requestBody:
        $ref: "./orders.post.yaml#/components/requestBodies/request"
      responses:
        200:
          $ref: "orders.post.yaml#/components/responses/Ok"
        400:
          description: |-
            ## Bad Request
            ### AKE0401
            注文IDが既に登録済み
        404:
          description: |-
            ## Not Found
            ### AKE0402
            電子部品IDが電子部品マスタに登録されていない
        500:
          description: |-
            ## Internal Server Error
            ### C999
            異常終了

    get:
      summary: 秋月電子の注文取得
      description: |
        ## 秋月電子の注文を取得する
      parameters:
        - $ref: ../common/models.yaml#/components/parameters/pageIndex
        - $ref: ../common/models.yaml#/components/parameters/pageSize
      tags:
        - "akizuki"
      operationId: get-orders
      responses:
        200:
          $ref: "./orders.get.yaml#/components/responses/Ok"
        204:
          description: NoContent
        500:
          description: TODO
