openapi: 3.0.3
info:
  title: ""
  version: "v1"
paths: {}
components:
  schemas:
    fetchComponentByAkizukiCatalogId:
      title: 秋月電子のカタログIDをもとに電子部品情報を返す
      allOf:
        - $ref: ../common/models.yaml#/components/schemas/baseResponse
        - type: object
          properties:
            data:
              title: FetchComponentByAkizukiCatalogIdData
              allOf:
                - $ref: ../parts-component/models.yaml#/components/schemas/partsComponent
              properties:
                categoryId:
                  $ref: "../parts-component/models.yaml#/components/schemas/categoryId"
                id:
                  writeOnly: true
                  allOf:
                    - $ref: "../parts-component/models.yaml#/components/schemas/componentId"
                category:
                  writeOnly: true
                  allOf:
                    - $ref: "../parts-component/models.yaml#/components/schemas/category"
                unRegistered:
                  title: 未登録情報
                  description: |-
                    本システムに未登録の以下がある
                    - makerId 未登録メーカーID
                    - category 未登録カテゴリー
                  type: object
                  properties:
                    makerId:
                      $ref: "../parts-component/models.yaml#/components/schemas/makerId"
                    category:
                      $ref: "../parts-component/models.yaml#/components/schemas/category"
              required:
                - images
