openapi: 3.0.3
info:
  title: ""
  version: "v1"
paths: {}
components:
  schemas:
    fetchComponentByAkizukiCatalogIdResponse:
      title: 秋月電子のカタログIDをもとに電子部品情報を返す
      allOf:
        - $ref: ../common/models.yaml#/components/schemas/baseResponse
        - type: object
          properties:
            data:
              title: FetchComponentByAkizukiCatalogIdData
              type: object
              properties:
                name:
                  $ref: "../parts-component/models.yaml#/components/schemas/componentName"
                modelName:
                  $ref: "../parts-component/models.yaml#/components/schemas/componentModelName"
                description:
                  $ref: "../parts-component/models.yaml#/components/schemas/componentDescription"
                images:
                  title: 電子部品画像リスト
                  type: array
                  items:
                    $ref: "../parts-component/models.yaml#/components/schemas/componentImageUrl"
                categoryId:
                  $ref: "../parts-component/models.yaml#/components/schemas/categoryId"
                makerName:
                  $ref: "../parts-component/models.yaml#/components/schemas/makerName"
                unRegistered:
                  title: 未登録情報
                  description: |-
                    本システムに未登録の以下がある
                    - makerName 未登録メーカー名
                    - category 未登録カテゴリー
                  type: object
                  properties:
                    makerName:
                      $ref: "../parts-component/models.yaml#/components/schemas/makerName"
                    category:
                      $ref: "../parts-component/models.yaml#/components/schemas/category"
              required:
                - name
                - modelName
                - description
                - images
                - makerName
                - categoryId
