openapi: 3.0.3
info:
  title: "common"
  version: "1.0"
paths: {}
components:
  schemas:
    pageIndex:
      title: ページ数
      type: integer
      minimum: 1
      default: 1
      example: 1
    pageSize:
      title: 表示数
      type: integer
      example: "10"
      minimum: 1
      default: 10
      description: 表示数
    totalPages:
      title: 全ページ数
      type: integer
      example: 10
      minimum: 0
    totalCount:
      title: 全件数
      type: integer
      minimum: 0
      example: 100
    hasNext:
      title: 次のページがあるかどうか
      type: boolean
    hasPrevious:
      title: 前のページがあるかどうか
      type: boolean
      default: false

    error:
      title: エラー
      type: object
      properties:
        message:
          title: メッセージ
          type: string
        code:
          title: エラーコード
          type: string
          example: null
      required:
        - message
      example: null

    baseResponse:
      title: レスポンス
      type: object
      properties:
        data:
          title: データ
          type: object
          readOnly: true
        error:
          $ref: "#/components/schemas/error"

    pageResponse:
      title: ページレスポンス
      allOf:
        - $ref: "#/components/schemas/baseResponse"
        - type: object
          description: ページネーションデータ
          properties:
            pageIndex:
              $ref: "#/components/schemas/pageIndex"
            pageSize:
              $ref: "#/components/schemas/pageSize"
            totalPages:
              $ref: "#/components/schemas/totalPages"
            totalCount:
              $ref: "#/components/schemas/totalCount"
            hasNext:
              $ref: "#/components/schemas/hasNext"
            hasPrevious:
              $ref: "#/components/schemas/hasPrevious"
          required:
            - pageIndex
            - pageSize
            - totalPages
            - totalCount
            - hasNext
            - hasPrevious

  parameters:
    pageIndex:
      name: pageIndex
      in: query
      schema:
        $ref: "#/components/schemas/pageIndex"
      allowEmptyValue: true
    pageSize:
      name: pageSize
      in: query
      schema:
        $ref: "#/components/schemas/pageSize"
      description: 表示数
      allowEmptyValue: true
    sortColumn:
      name: sortColumn
      in: query
      required: false
      schema:
        type: string
        example: ComponentName
      description: ソートするカラム名
    sortOrder:
      name: sortOrder
      in: query
      schema:
        type: string
        enum:
          - ASC
          - DESC
        example: ASC
      description: ソート順(ASC、DESC)
    filterColumn:
      name: filterColumn
      in: query
      required: false
      schema:
        type: string
      description: フィルター項目
    filterQuery:
      name: filterQuery
      in: query
      required: false
      schema:
        type: string
      description: フィルター内容
