openapi: 3.0.3
info:
  title: ""
  version: "1.0"
paths: {}
components:
  schemas:
    pageIndex:
      title: ページ数
      type: integer
      minimum: 0
      default: 0
      example: 0
    pageSize:
      title: 表示数
      type: integer
      example: "10"
      minimum: 1
      default: 10
      description: 表示数
    totalPages:
      title: 全ページ数
      type: integer
      example: 10
      minimum: 0
    totalCount:
      title: 全件数
      type: integer
      minimum: 0
      example: 100
    hasNext:
      title: 次のページがあるかどうか
      type: boolean
    hasPrevious:
      title: 前のページがあるかどうか
      type: boolean
      default: false

    errorResponse:
      type: object
      title: エラー情報
      description: |-
        ## エラー情報
        ### C400
        入力パラメーターエラー

        ### C401
        認証失敗エラー

        ### C999
        異常終了時のエラー
        このパターンのみ`stack`に値が入る

        ### AKE0101
        API固有のエラー

        先頭の2文字がAPIの頭文字
        3文字目のEは`Error`の`E`
        最後の数字の最初の2桁はAPIのHttpStatusCodeごとに繰り上がる
        #### 例
        - HttpStatusCode 400
          - エラー1つ目 `0101`
          - エラー2つ目 `0102`
        - HttpStatusCode 404
          - エラー1つ目 `0201`
          - エラー2つ目 `0202`
      properties:
        data:
          type: object
          default: null
          readOnly: true
        code:
          title: エラーコード
          type: string
          example: AKE0101
          default: C999
          minLength: 4
          description: エラーコード
          readOnly: true
        message:
          title: エラーメッセージ
          type: string
          example: 予期せぬエラーが発生しました
          description: エラーメッセージ
          readOnly: true
        stack:
          type: string
          description: StackTraceの内容 C999の場合のみ
          readOnly: true
          example: IOException StreamReader.Read at 102 line...
      required:
        - code
        - message
    successResponse:
      title: 成功
      type: object
      description: |-
        成功時のレスポンス
      properties:
        data:
          type: object
          description: データ
          readOnly: true
      required:
        - data

    successPageResponse:
      title: ページ情報付き成功レスポンス
      allOf:
        - $ref: "#/components/schemas/successResponse"
        - type: object
          description: ページネーションデータ
          properties:
            pageIndex:
              $ref: "#/components/schemas/pageIndex"
            pageSize:
              $ref: "#/components/schemas/pageSize"
            totalPages:
              $ref: "#/components/schemas/totalPages"
            totalCount:
              $ref: "#/components/schemas/totalCount"
            hasNext:
              $ref: "#/components/schemas/hasNext"
            hasPrevious:
              $ref: "#/components/schemas/hasPrevious"
          required:
            - pageIndex
            - pageSize
            - totalPages
            - totalCount
            - hasNext
            - hasPrevious

  parameters:
    page-index:
      name: pageIndex
      in: query
      schema:
        $ref: "#/components/schemas/pageIndex"
      allowEmptyValue: true
    page-size:
      name: pageSize
      in: query
      schema:
        $ref: "#/components/schemas/pageSize"
      description: 表示数
      allowEmptyValue: true
    sort-column:
      name: sortColumn
      in: query
      required: false
      schema:
        type: string
        example: ComponentName
      description: ソートするカラム名
    sort-order:
      name: sortOrder
      in: query
      schema:
        type: string
        enum:
          - ASC
          - DESC
        example: ASC
      description: ソート順(ASC、DESC)
    filter-column:
      name: filter-column
      in: query
      required: false
      schema:
        type: string
      description: フィルター項目
    filter-query:
      name: filter-query
      in: query
      required: false
      schema:
        type: string
      description: フィルター内容
